framework:
    secret: '%kernel.secret%'
    http_method_override: false
    php_errors:
        log: true
    session:
        enabled: true
        handler_id: null
        name: phpList4_session
        cookie_secure: auto
        cookie_samesite: lax
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers: ~
        # Force Symfony to scan our custom public files path via empty files in translations/
